### ISSUE TITLE
Baseline code

### ISSUE THREAD

**Issue by basma-b** [cooelf/DeepUtteranceAggregation#4]
Please can you share the code source you used to reproduce the baseline results on your new dataset ?

**Comment by cooelf** [comment]
Sorry that I don’t have a plan to clean the code in the short term. They are easy to implement, some of them are revised from these repos. 
https://github.com/fuhuamosi/MatchLstm
https://github.com/coderbyr/MV-LSTM
https://github.com/divishdayal/Attentive_LSTM_question-answering
https://github.com/codekansas/keras-language-modeling

**Comment by basma-b** [comment]
Thank you for the link, it'd be appreciated if you can share the code you used to produce those baseline scores when you have time for reproducibility matters.
