### ISSUE TITLE
original taobao data.

### ISSUE THREAD

**Issue by BobCN2017** [cooelf/DeepUtteranceAggregation#6]
the data about taobao is tokenized, do you have the original data, not tokenized, if you have, could you please give the original data to me. if possible, it is ok to give a url or send to me,  my e-mail is zhangp365@gmail.com, thank you very much.

**Comment by cooelf** [comment]
Sorry we could not provide the original data since they are unmasked with sensitive information . Maybe you can simply remove the spaces?
