### ISSUE TITLE
About the pretrained word2vec model you used.

### ISSUE THREAD

**Issue by Coldog2333** [cooelf/DeepUtteranceAggregation#7]
Hello, thank you for sharing the E-commerce dataset!
However, about the pretrained word2vec model, I could only find a script in this repository but it seems insufficient for reproducing the result of your paper. Could I ask the word2vec model you used or could you please tell me how did you pretrain the word embedding model? (the setting, the hyperparameters, the training dataset, etc. )

**Comment by cooelf** [comment]
Just notice the comment. It has been a long time since the work was done, I could not find the model now. But in my memory, it was trained using Skip-gram with the default parameters on the raw dataset.
