### ISSUE TITLE
'An update must have the same type as the original shared variable...

### ISSUE THREAD

**Issue by Ailing-Zou** [cooelf/DeepUtteranceAggregation#8]
When I process this code using 'bash train.sh' , the error appears.

<img width="546" alt="rBAoL13gheOACsYMAAEbIbD-pkY990" src="https://user-images.githubusercontent.com/52034091/69840129-67419600-1295-11ea-92b1-e0eea71eef78.png">

**Comment by MingYates** [comment]
the same error happens to me. 
have it been solved?

**Comment by cooelf** [comment]
Have you followed the recommended version of dependencies? It seems to be a version issue. Maybe you can check the version or try THEANO_FLAGS='floatX=float32'.

Our enviroment when this work was done:

Theano 0.9.0
Cuda 8.0
Cudnn 5.1
Numpy 1.13.3

**Comment by MingYates** [comment]
THEANO_FLAGS='floatX=float32'
works for me, thanks so much.

**Comment by Ailing-Zou** [comment]
Thx very much
