### ISSUE TITLE
python PreProcess.py --train_dataset ./ECD_sample/train --valid_dataset ./ECD_sample/valid --test_dataset ./ECD_sample/test --pretrained_embedding embedding --save_dataset ./ECD_sample/all

### ISSUE THREAD

**Issue by iskaliyang** [cooelf/DeepUtteranceAggregation#9]
Traceback (most recent call last):
  File "PreProcess.py", line 206, in <module>
    ParseMultiTurn()
  File "PreProcess.py", line 200, in ParseMultiTurn
    word2vec = WordVecs(args.pretrained_embedding, vocab, True, True)
  File "PreProcess.py", line 114, in __init__
    self.W, self.word_idx_map = self.get_W(word_vecs, k=self.k)
  File "PreProcess.py", line 127, in get_W
    W[i] = word_vecs[word]
ValueError: could not broadcast input array from shape (200) into shape (2582)

what should i do now.somebody help me out.please

**Comment by cooelf** [comment]
Please check your pre-trained embedding. The dimension (2582) seems not to match with the default one (200)

https://github.com/cooelf/DeepUtteranceAggregation/blob/master/PreProcess.py#L110
